// Generated by Lasy AI - https://lasy.ai
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
// Import all available fonts for AI usage
import "../lib/fonts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SHAPEZONE - Desafio 15 Dias no Shape",
  description: "Personal trainer + nutricionista por IA. Plano personalizado, correção de exercícios e resultados reais por R$34,90",
  keywords: "fitness, treino, dieta, personal trainer, nutricionista, IA, emagrecimento, musculação",
  authors: [{ name: "SHAPEZONE" }],
  openGraph: {
    title: "SHAPEZONE - Desafio 15 Dias no Shape",
    description: "Transforme seu corpo em 15 dias com personal trainer e nutricionista por IA",
    type: "website",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <Script src="/lasy-bridge.js" strategy="beforeInteractive" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
